---
title: "cma_exercise4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Prep Tasks

```{r}

testfun <- function(){
  print("hello world")
}

testfun()


testfun <- function(x){
  print(x)
}

testfun("hi guys")

my_age <- function(birthday, units){
  difftime(Sys.time(), birthday, units = units)
}

my_age("1995-05-23", "hours")


```

Task 1: Writing euclidian distance function

```{r}
euclidian_distance <- function(x1, y1, x2, y2){ 
  sqrt((x1-x2)^2+(y1-y2)^2)
}
```

Task 2: Prepare Analysis

```{r}
library(readr)        
library(dplyr)        
library(ggplot2)      
library(lubridate)

```

Task 3: Create Join Key

```{r}

#reading in the data
wildschwein <- read_delim("data/wildschwein_BE_2056.txt", ",")

#rounding time
wildschwein <- wildschwein %>% 
  mutate(roundtime_15 = round_date(DatetimeUTC,"15mins"))

```

Task 4: Measuring distance at concurrent locations

```{r}
split_by_individual <- split(wildschwein, wildschwein$TierID)
Sabi <- split_by_individual[["002A"]]
Rosa <- split_by_individual[["016A"]]
Ruth <- split_by_individual[["018A"]]

joined_indivduals <- inner_join(Sabi, Rosa, "roundtime_15", suffix = c(".Sabi", ".Rosa"))
#Picked inner_joins as this only keeps data that has a matching key, cuts down on data size too.

joined_indivduals <- joined_indivduals %>%
  mutate(
    individ_dist = euclidian_distance(E.Sabi, N.Sabi, E.Rosa, N.Rosa),
    meets = ifelse(individ_dist <= 100, TRUE, FALSE),
    E = (E.Sabi + E.Rosa)/2, #Point in the middle when meeting
    N = (N.Sabi + N.Rosa)/2
  )

#Tiying up the dataframe
meeting_points <- subset(joined_indivduals, meets == TRUE, select = c(E.Sabi, N.Sabi, E.Rosa, N.Rosa, individ_dist, roundtime_15, meets, E, N))

```


Task 5: Visualize data

```{r}
wildschwein_subset <- subset(wildschwein, TierName == "Sabi" | TierName == "Rosa" )

ggplot()+
  geom_point(data = wildschwein_subset, aes(x = E, y = N, color = TierName), alpha = 0.2, inherit.aes = F)+
  geom_point(data = meeting_points, aes(x = E, y = N, colour = meet), shape = 1, fill = NA, color = "black")+
  xlim(2569250, 2571000)+
  ylim(1204000, 1206500)+
  coord_fixed()
    
        
```


